// https://storage.googleapis.com/seh-bees/images/0001a259-8e70-4751-907e-ea4f89e1de67.jpg

<script setup>
  import { ref } from 'vue'
  import myData from '../assets/data/detections-genus-matched.json' 


  // const items = ref(myData)

</script>


<template>
	<h3>{{matches.length}} of {{items.length}} bee-plant observations > <input v-model="minScore" type="number" min="0" max="0.9" step="0.1"></h3>
	<p>Observations are from the ALA, superfamily Apoidea, Southern Highlands bioregion. Plant IDs are generated by <a href="https://imageomics.github.io/bioclip-2/">BioCLIP 2</a>.</p>
<div class="facets">
	<FacetList :list-data="beeGenera" facet="bee" facet-title="Bees" :filter-state="filter" @set-filter="setFilter"></FacetList>
	<FacetList :list-data="plantGenera" :filter-state="filter" facet="plant" facet-title="Plants" @set-filter="setFilter"></FacetList>
</div>

	<h4>{{Math.min(viewSize,viewItems.length)}} of {{viewItems.length}} observations 

	 		<span v-if="filter.bee || filter.plant">for </span>
	 		<span v-if="filter.bee">bee genus 
	 			<span class="filterChip">{{filter.bee}} <button class="close-unicode" aria-label="Close" @click="unsetFilter('bee')"></button></span>
	 		</span>
	 		<span v-if="filter.bee && filter.plant"> and </span>
	 		<span v-if="filter.plant">plant genus 
	 			<span class="filterChip">{{filter.plant}} <button class="close-unicode" aria-label="Close" @click="unsetFilter('plant')"></button></span>
	 		</span>
	 	</h4>

	 <ul class="items">


	    <li v-for="item in viewItems.slice(0,viewSize)" class="item">
	      <img :src="'https://storage.googleapis.com/seh-bees/images/'+item.imageID+'.jpg'">
	      <div class="metadata">
	      	<p>bee: <em>{{item.scientificName}}</em></p>
	      	<p>plant: <span v-for="p in item.plantDetections">
	      	{{p.genus}}: {{p.score.toFixed(2)}} | 
	      	</span>
	      	</p>
	      	<p><a :href="item.occurrenceID" target="_blank">source</a></p>

	  	</div>

	    </li>
	    <div class="morebutton" v-if="viewItems.length > viewSize"> <button @click="viewSize += 100">Show more</button></div>
  	</ul>
</template>

<script>
	  import FacetList from './components/FacetList.vue'

export default {

  name: 'App',

  components:{ 
  	FacetList 
  },

  data () {
    return {
    	items:myData,
    	filter: {bee:null, plant:null},
    	minScore:0.4,
    	viewSize:100,
    }
  },
  computed:{

  	matches(){
  		return this.items.filter(i => i.plantDetections[0].score > this.minScore)
  	},
  	
  	beeGenera(){

  		let sourceItems = this.matches;
  		if (this.filter.plant) sourceItems = sourceItems.filter(i => i.plantDetections[0].genus == this.filter.plant) 
  			// filter by plant filter if present

  		const allGenusSet = new Set(sourceItems.map(i => i.genus));
  		const allGenus = [...allGenusSet];
  		const genusFacets = allGenus.map(g => { 
  			return {genus:g, detections: sourceItems.filter(i => i.genus == g)}
  		});
  		return genusFacets;
  	},

  	plantGenera(){
  		let sourceItems = this.matches;
  		if (this.filter.bee) sourceItems = sourceItems.filter(i => i.genus == this.filter.bee) 
  			// filter by bee filter if present

  		const allGenusSet = new Set(sourceItems.map(i => i.plantDetections[0].genus));
  		const allGenus = [...allGenusSet];
  		const genusFacets = allGenus.map(g => { 
  			return {genus:g, detections: sourceItems.filter(i => i.plantDetections[0].genus == g)}
  		});
  		return genusFacets;
  	},

  	viewItems(){
  		let filtered = this.matches;

  		if (this.filter.bee) filtered = this.matches.filter(i => i.genus == this.filter.bee)

  		if (this.filter.plant) filtered = filtered.filter(i => i.plantDetections[0].genus == this.filter.plant)

  		return filtered.sort((a,b) => a.plantDetections[0].score - b.plantDetections[0].score);
  	}

  },

  methods:{
  	setBeeFilter(beeGenus){
  		if (this.filter.bee == beeGenus) {
  			this.filter.bee = ""
  			return;
  		}
  		this.filter.bee = beeGenus;
  	},
  	setPlantFilter(plantGenus){
  		if (this.filter.plant == plantGenus) {
  			this.filter.plant = ""
  			return;
  		}
  		this.filter.plant = plantGenus
  	},

  	setFilter(facet,value){
  		this.viewSize = 100;
  		if (facet == "bee") this.setBeeFilter(value);
  		if (facet == "plant") this.setPlantFilter(value);
  	},

  	unsetFilter(field){
  		this.filter[field] = "";
  	}
  }
}
</script>

<style lang="css" scoped>


ul.items{
	display: flex;
	flex-direction: row;
	flex-wrap: wrap;
	align-items: flex-start;
	margin:0;
	padding:0;
}

 .beeFilter{
 	display: inline-block;
 	padding:0.25rem;
 	margin:0.25rem 0.25rem;
 	cursor: pointer;
 	background-color: #eee;
 }

 .item{
 	list-style: none;
 	display: inline-block;
 	width:240px;
 	margin:0.5rem;
 	padding:1.5rem;
 	background-color: #eaeae0;
 }

  .item .metadata {
  	font-weight: 300;
  	font-size:80%;
  }

  .metadata p{
  	margin:0.5rem 0;
  }

 .item img{
 	width:100%;
 	aspect-ratio: 1;
 	object-fit: cover;
 	display: block;
 	margin:0 auto;
 }

 .beeFilter.active{
 	background-color: lightcoral;
 }

.facets{
 	display: flex;
 	flex-wrap: nowrap;
 	flex-direction: row;
 }

 .filterChip{
 	background-color: #929281;
 	color:white;
 	font-style: italic;
 	font-weight:400;
 	padding:0.25rem 0 0.25rem 0.5rem;
 }

 .close-unicode {
  background: none;
  border: none;
  cursor: pointer;
  padding: 0 0.5rem 0 0.25rem;
  font-size: 20px; /* Adjust size of the 'X' */
  line-height: 0;
  position:relative;
  top:0.125rem;
}

/* Insert the X symbol using the 'times' ISO code */
.close-unicode::after {
  content: "\00d7"; /* Unicode character for × */
  color: black;
  opacity: 0.6;
}

/* Optional hover feedback */
.close-unicode:hover::after {
  opacity:1.0;
}

.morebutton{
	width:100%;
	text-align: center;
}

.morebutton button{
	color:white;
	background-color: #929281;
	border:none;
	border-radius: 0;
	padding:0.5rem;
	font-weight: 600;
	cursor:pointer;
	opacity:0.8;

}

.morebutton button:hover{
	opacity:1.0;
}

</style>

<!--Taraxacum  https://id.biodiversity.org.au/taxon/apni/51748197 -->